app = "one-bot-tele"
primary_region = "sin"

[build]

[processes]
app = "python main.py"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
